### ISSUE TITLE
Issues building due to missing methods

### ISSUE THREAD

**Issue by mamaar** [vfx-rs/oiio-bind#39]
I have issues building the library and get this:

    cargo:warning=src/ffi_imagebuf.cpp:719:14: error: no member named 'lock' in 'OpenImageIO_v2_5::ImageBuf'
    cargo:warning=    imagebuf.lock();
    cargo:warning=    ~~~~~~~~ ^
    cargo:warning=src/ffi_imagebuf.cpp:725:14: error: no member named 'unlock' in 'OpenImageIO_v2_5::ImageBuf'
    cargo:warning=    imagebuf.unlock();
    cargo:warning=    ~~~~~~~~ ^

It builds after I remove all references to these methods in .cpp, .h, and .rs files.

I cannot see the mentioned methods in the C++ API, so maybe I can make a PR that removes them.

**Comment by lgritz** [comment]
Oops, that's my fault. It's documented in imagebuf.h but I didn't do the special incantation to ensure it was listed in the generated docs.

**Comment by mamaar** [comment]
Aha, my fault. Lock and unlock are relatively new additions. I just saw the latest release date and thought I had a new version, but it seems like you added these methods for a future 2.6 and they are not in 2.5.x.x.

I installed OIIO from HEAD and it works now. Thanks!
